# node:24-alpine ( imagens oficiais do Docker )
#  mysql:8.4.5

services:
  nodejs: # nome do serviço
    image: node:24-alpine # imagem do container
    container_name: nodejs # nome do container
    working_dir: /app # diretório de trabalho dentro do container
    volumes: # volume de persistência
      - ./volume_app:/app # mapeia o diretório local para o diretório de trabalho do container
    ports: # mapeamento de portas
      - "3000:3000" # mapeia a porta 3000 do host para a porta 3000 do container
    command: sh # inicia o container executando o shell (sh)
    stdin_open: true # persistencia do sh aberto, (interação com o terminal)
    tty: true # aloca um terminal virtual para o container
    networks:
      - nodejs_network # conecta o container à rede definida abaixo


# servico mysql
  nodejs_mysql:
     image: mysql:8.4.5
     container_name: nodejs_mysql
     environment:
        MYSQL_ROOT_PASSWORD: root # senha do usuário root do MySQL
     ports:
        - "3306:3306" # mapeia a porta 3306 do host para a porta 3306 do container
     volumes:
        - ./volume_data:/var/lib/mysql # mapeia o volume de dados do MySQL
     networks:
        - nodejs_network # conecta o container à mesma rede do serviço Node.js


networks: # rede para os containers
  nodejs_network: # nome da rede
    driver: bridge # tipo de rede, neste caso, uma rede bridge
    name: nodejs_network # nome da rede


